version: "3.1"
services:
  web:
    image: maki/modx
    links:
      - "db:mysql"
    ports:
      - "86:80"
    environment:
      MODX_VERSION: 2.7.0
      MODX_DB_HOST: "mysql:3306"
      MODX_DB_PASSWORD: modx
      MODX_DB_USER: modx
      MODX_DB_NAME: modx
    volumes:
      - "./html:/var/www/html"
  db:
    image: "mariadb:10.6.4"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: modx
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: modx
    ports:
      - "3306:3306"
    volumes:
      - "./mariadb:/var/lib/mariadb"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: modx
    restart: always
    ports:
      - 8086:80
